Repository Kernel360/E2E1-Boogle, pull requests merged in 2023-11, with the labels that each got.

#88 Feature/login 로그인 기능 추가했습니다.
  build.gradle
  src/main/java/com/kernel360/boogle/book/controller/BookController.java
  src/main/java/com/kernel360/boogle/security/config/CustomSecurityConfig.java
  src/main/java/com/kernel360/boogle/security/controller/SecurityController.java
  src/main/java/com/kernel360/boogle/security/service/CustomUserDetailsService.java
  src/main/resources/templates/book/admin/book-create.html
  src/main/resources/templates/book/admin/book-list.html
  src/main/resources/templates/login.html
Labels: enhancement

#91 [feat] #77 BookReport(독후감) 구현
  src/main/java/com/kernel360/boogle/book/controller/BookController.java
  src/main/java/com/kernel360/boogle/book/service/BookServiceImpl.java
  src/main/java/com/kernel360/boogle/bookreport/controller/BookReportController.java
  src/main/java/com/kernel360/boogle/bookreport/db/BookReportEntity.java
  src/main/java/com/kernel360/boogle/bookreport/model/BookReportDTO.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportServiceImpl.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/book/admin/book-create.html
  src/main/resources/templates/book/admin/book-update.html
  src/main/resources/templates/bookreport/book-report-create.html
  src/main/resources/templates/bookreport/book-report-detail.html
  src/main/resources/templates/bookreport/book-report-update.html
  src/main/resources/templates/bookreport/book-reports.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/navbar.html
Labels: enhancement

#95 [feat] add Reply structure, ReplyEntity
  src/main/java/com/kernel360/boogle/reply/controller/ReplyController.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyEntity.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
  src/main/java/com/kernel360/boogle/reply/model/ReplyDTO.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyServiceImpl.java
Labels: :arrow_up: enhancement

#103 [feat] Reply(댓글/대댓글) 화면 연결 및 삭제 리팩토링
  src/main/java/com/kernel360/boogle/bookreport/controller/BookReportController.java
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/java/com/kernel360/boogle/reply/controller/ReplyController.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyEntity.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
  src/main/java/com/kernel360/boogle/reply/model/ReplyDTO.java
  src/main/java/com/kernel360/boogle/reply/model/ReplyResponse.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyServiceImpl.java
  src/main/resources/templates/bookreport/book-report-detail.html
Labels: :arrow_up: enhancement

#106 [feat] Pagination & Style 수정
  src/main/resources/templates/book/admin/book-create.html
  src/main/resources/templates/book/admin/book-update.html
  src/main/resources/templates/book/admin/books.html
  src/main/resources/templates/bookreport/admin/book-report-detail.html
  src/main/resources/templates/bookreport/admin/book-reports.html
  src/main/resources/templates/bookreport/book-reports.html
  src/main/resources/templates/fragments/navbar.html
Labels: :arrow_up: enhancement, :hammer_and_wrench: refactoring

#107 [feat] Book Report 테스트코드 반영
  .gitignore
  src/main/java/com/kernel360/boogle/bookreport/controller/BookReportController.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/kernel360/boogle/bookreport/db/BookReportRepositoryTest.java
  src/test/java/com/kernel360/boogle/bookreport/service/BookReportServiceTest.java
  src/test/resources/db/migration/V3.0.8.1__insert_test_book_data.sql
  src/test/resources/db/migration/V3.0.8.2__insert_test_bookreport_data.sql
  src/test/resources/db/migration/V3.0.8.3__insert_test_member_data.sql
Labels: :arrow_up: enhancement

#108 [feat] nav, signup, login 화면 관련 수정
  src/main/java/com/kernel360/boogle/member/controller/SignupController.java
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: :arrow_up: enhancement

#110 [feat] DB 테이블 추가 및 컬럼 정보 수정
  src/main/resources/db/migration/V3.0.5__add_reply_table.sql
  src/main/resources/db/migration/V3.0.6__add_column_in_member.sql
  src/main/resources/db/migration/V3.0.7__alter_column_in_member.sql
  src/main/resources/db/migration/V3.0.8__alter_column_in_reply.sql
Labels: :package: db

#111 [feat] bookReport 유저 화면 로고 추가 및 디자인 수정
  src/main/resources/static/images/logo.png
  src/main/resources/templates/bookreport/book-reports.html
Labels: :arrow_up: enhancement

#114 [feat & refactor] 도서 조회 기능/화면(USER) 구현 & ServiceImpl 삭제 리팩토링
  src/main/java/com/kernel360/boogle/book/controller/BookController.java
  src/main/java/com/kernel360/boogle/book/service/BookService.java
  src/main/java/com/kernel360/boogle/book/service/BookServiceImpl.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportServiceImpl.java
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/resources/templates/book/book-detail.html
  src/main/resources/templates/book/books.html
  src/main/resources/templates/fragments/navbar.html
Labels: :arrow_up: enhancement, :hammer_and_wrench: refactoring

#122 [feat] 주간 회원 유입 통계 (관리자)
  src/main/java/com/kernel360/boogle/BoogleApplication.java
  src/main/java/com/kernel360/boogle/member/db/MemberRepository.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/business/MemberInflowAggregation.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/controller/MemberInflowController.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/db/MemberInflowEntity.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/db/MemberInflowRepository.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/model/MemberInflowDTO.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/scheduler/MemberInflowScheduler.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/scheduler/legacy/MemberInflowSchedulerLegacy.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/service/MemberInflowConverter.java
  src/main/java/com/kernel360/boogle/statistics/memberinflow/service/MemberInflowService.java
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/statistics/admin/statistics-admin-dashboard.html
  src/test/java/com/kernel360/boogle/member/service/MemberServiceTest.java
  src/test/java/com/kernel360/boogle/statistics/memberinflow/business/MemberInflowAggregationTest.java
  src/test/java/com/kernel360/boogle/statistics/memberinflow/db/MemberInflowRepositoryTest.java
  src/test/java/com/kernel360/boogle/statistics/memberinflow/service/MemberInflowServiceTest.java
Labels: :arrow_up: enhancement, :package: db

#123 [feat] yml 환경별 분리 및 Jasypt 적용
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/kernel360/boogle/bookreport/db/BookReportRepositoryTest.java
  src/test/java/com/kernel360/boogle/bookreport/service/BookReportServiceTest.java
  src/test/resources/application.yml
  src/test/resources/db/test-migration/V1.0.0__init.sql
  src/test/resources/db/test-migration/V1.0.1__insert_test_book_data.sql
  src/test/resources/db/test-migration/V1.0.2__insert_test_bookreport_data.sql
  src/test/resources/db/test-migration/V1.0.3__insert_test_member_data.sql
Labels: :arrow_up: enhancement

#129 [feat] 마이페이지구현, 회원정보수정페이지구현
  src/main/java/com/kernel360/boogle/book/controller/BookAdminController.java
  src/main/java/com/kernel360/boogle/book/service/BookService.java
  src/main/java/com/kernel360/boogle/bookreport/db/BookReportRepository.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/java/com/kernel360/boogle/member/db/MemberRepository.java
  src/main/java/com/kernel360/boogle/member/model/MemberSignupDTO.java
  src/main/java/com/kernel360/boogle/member/service/MemberService.java
  src/main/java/com/kernel360/boogle/mypage/controller/MyPageController.java
  src/main/java/com/kernel360/boogle/mypage/model/MemberRequestDTO.java
  src/main/java/com/kernel360/boogle/mypage/service/MyPageService.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
  src/main/resources/static/css/styles.css
  src/main/resources/templates/book/books.html
  src/main/resources/templates/bookreport/book-reports.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/mypage/bookReport.html
  src/main/resources/templates/mypage/communityReply.html
  src/main/resources/templates/mypage/main.html
  src/main/resources/templates/mypage/memberInfo.html
  src/main/resources/templates/register.html
Labels: :arrow_up: enhancement

#130 [feat] aws codedeploy 관련 설정 추가
  .github/workflows/build.yml
  appspec.yml
  scripts/deploy.sh
  src/main/resources/logback-spring.xml
Labels: :arrow_up: enhancement

#131 [feat & refactor] Reply(댓글) 구현 고도화 및 Reply관련 리팩토링
  src/main/java/com/kernel360/boogle/global/GlobalExceptionHandler.java
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/java/com/kernel360/boogle/reply/controller/ReplyController.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyEntity.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
  src/main/java/com/kernel360/boogle/reply/exception/EmptyContentException.java
  src/main/java/com/kernel360/boogle/reply/model/ReplyDTO.java
  src/main/java/com/kernel360/boogle/reply/model/ReplyResponse.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
  src/main/resources/templates/bookreport/book-report-detail.html
Labels: :arrow_up: enhancement, :hammer_and_wrench: refactoring

#136 [feat] DB 테이블 수정사항 관련 flyway SQL 반영
  src/main/resources/db/migration/V3.0.10__add_column_in_tables.sql
  src/main/resources/db/migration/V3.0.11__drop_column_in_member.sql
  src/main/resources/db/migration/V3.0.9__add_fk_in_reply.sql
  src/test/resources/db/test-migration/V1.0.4__drop_column_in_member.sql
Labels: :package: db

#137 [feat] Custom Exception 처리 구조 변경
  src/main/java/com/kernel360/boogle/global/GlobalExceptionHandler.java
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/java/com/kernel360/boogle/global/error/GlobalExceptionHandler.java
  src/main/java/com/kernel360/boogle/global/error/code/ErrorCode.java
  src/main/java/com/kernel360/boogle/global/error/code/MemberErrorCode.java
  src/main/java/com/kernel360/boogle/global/error/code/ReplyErrorCode.java
  src/main/java/com/kernel360/boogle/global/error/dto/ErrorResponse.java
  src/main/java/com/kernel360/boogle/global/error/exception/BusinessException.java
  src/main/java/com/kernel360/boogle/member/controller/SignupController.java
  src/main/java/com/kernel360/boogle/member/exception/AlreadySignedupMemberException.java
  src/main/java/com/kernel360/boogle/member/exception/MemberNotFoundException.java
  src/main/java/com/kernel360/boogle/member/service/MemberService.java
  src/main/java/com/kernel360/boogle/reply/controller/ReplyController.java
  src/main/java/com/kernel360/boogle/reply/exception/EmptyContentException.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
  src/test/java/com/kernel360/boogle/member/service/MemberServiceTest.java
Labels: :arrow_up: enhancement, :hammer_and_wrench: refactoring

#141 [fix] jar 실행 시, 로그 경로 잘못된 부분 수정
  scripts/deploy.sh
Labels: :building_construction: setting

#140 feat: refresh token
  src/main/java/com/kernel360/boogle/book/db/BookEntity.java
  src/main/java/com/kernel360/boogle/book/db/BookRepository.java
  src/main/java/com/kernel360/boogle/book/service/BookConverter.java
  src/main/java/com/kernel360/boogle/book/service/BookService.java
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/java/com/kernel360/boogle/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/kernel360/boogle/global/jwt/JwtAuthorizationFilter.java
  src/main/java/com/kernel360/boogle/global/jwt/JwtProperties.java
  src/main/java/com/kernel360/boogle/global/jwt/JwtUtils.java
  src/main/java/com/kernel360/boogle/member/model/MemberSignupDTO.java
Labels: :arrow_up: enhancement

#142 [feat & refactor]
  src/main/java/com/kernel360/boogle/book/controller/BookAdminController.java
  src/main/java/com/kernel360/boogle/book/db/BookRepository.java
  src/main/java/com/kernel360/boogle/book/model/BookDTO.java
  src/main/java/com/kernel360/boogle/book/service/BookService.java
  src/main/java/com/kernel360/boogle/bookreport/controller/BookReportAdminController.java
  src/main/java/com/kernel360/boogle/bookreport/controller/BookReportController.java
  src/main/java/com/kernel360/boogle/bookreport/db/BookReportEntity.java
  src/main/java/com/kernel360/boogle/bookreport/db/BookReportRepository.java
  src/main/java/com/kernel360/boogle/bookreport/model/BookReportDTO.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
  src/main/java/com/kernel360/boogle/member/model/MemberDTO.java
  src/main/java/com/kernel360/boogle/reply/controller/ReplyController.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
  src/main/resources/db/migration/V3.0.12__alter_column_in_book.sql
  src/main/resources/db/migration/V3.0.13__alter_column_in_book_report.sql
  src/main/resources/templates/book/admin/book-update.html
  src/main/resources/templates/book/admin/books.html
  src/main/resources/templates/bookreport/admin/book-report-detail.html
  src/main/resources/templates/bookreport/book-report-detail.html
Labels: :arrow_up: enhancement, :hammer_and_wrench: refactoring

#143 [feat & refactor] BookReport(독후감) MemberEntity 연결 및 기타 리팩토링
  src/main/java/com/kernel360/boogle/bookreport/controller/BookReportAdminController.java
  src/main/java/com/kernel360/boogle/bookreport/controller/BookReportController.java
  src/main/java/com/kernel360/boogle/bookreport/db/BookReportEntity.java
  src/main/java/com/kernel360/boogle/bookreport/db/BookReportRepository.java
  src/main/java/com/kernel360/boogle/bookreport/model/BookReportDTO.java
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
  src/main/java/com/kernel360/boogle/reply/db/ReplyRepository.java
  src/main/java/com/kernel360/boogle/reply/service/ReplyService.java
  src/main/resources/templates/book/admin/book-create.html
  src/main/resources/templates/book/admin/book-update.html
  src/main/resources/templates/book/admin/books.html
  src/main/resources/templates/book/book-detail.html
  src/main/resources/templates/book/books.html
  src/main/resources/templates/bookreport/admin/book-report-detail.html
  src/main/resources/templates/bookreport/admin/book-reports.html
  src/main/resources/templates/bookreport/book-report-create.html
  src/main/resources/templates/bookreport/book-report-detail.html
  src/main/resources/templates/bookreport/book-report-update.html
  src/main/resources/templates/bookreport/book-reports.html
  src/main/resources/templates/login.html
  src/main/resources/templates/mypage/bookReport.html
  src/main/resources/templates/mypage/communityReply.html
  src/main/resources/templates/mypage/main.html
  src/main/resources/templates/register.html
  src/main/resources/templates/statistics/admin/statistics-admin-dashboard.html
  src/test/java/com/kernel360/boogle/bookreport/db/BookReportRepositoryTest.java
  src/test/java/com/kernel360/boogle/bookreport/service/BookReportServiceTest.java
Labels: :arrow_up: enhancement, :hammer_and_wrench: refactoring

#144 [fix] 도서 상세페이지 조회 안 되던 이슈 해결
  src/main/java/com/kernel360/boogle/book/controller/BookController.java
  src/main/resources/templates/book/book-detail.html
  src/main/resources/templates/bookreport/book-report-create.html
  src/main/resources/templates/bookreport/book-report-detail.html
  src/main/resources/templates/bookreport/book-report-update.html
Labels: :rotating_light: bugfix

#164 [fix] Bug fix (#148, #150, #152, #155, #159, #162)
  src/main/java/com/kernel360/boogle/book/controller/BookController.java
  src/main/java/com/kernel360/boogle/book/db/BookRepository.java
  src/main/java/com/kernel360/boogle/book/service/BookService.java
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/resources/templates/bookreport/book-report-create.html
  src/main/resources/templates/bookreport/book-reports.html
  src/main/resources/templates/fragments/navbar.html
Labels: :zap: bugfix

#166 [feat] aop를 이용한 로깅
  build.gradle
  src/main/java/com/kernel360/boogle/BoogleApplication.java
  src/main/java/com/kernel360/boogle/global/aop/LogAspect.java
Labels: :arrow_up: enhancement

#167 [feat] url 경로 관련 수정
  src/main/java/com/kernel360/boogle/global/config/SpringSecurityConfig.java
  src/main/java/com/kernel360/boogle/global/config/WebConfig.java
  src/main/java/com/kernel360/boogle/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/kernel360/boogle/member/controller/LoginController.java
Labels: :arrow_up: enhancement

#168 [feat] 독후감 작성 & 마이페이지 기능 고도화
  src/main/java/com/kernel360/boogle/bookreport/service/BookReportService.java
  src/main/resources/templates/bookreport/book-report-create.html
  src/main/resources/templates/mypage/main.html
Labels: :arrow_up: enhancement

#172 feat: 로그인 유효성 검사 추가
  src/main/java/com/kernel360/boogle/global/jwt/JwtAuthenticationFilter.java
  src/main/resources/templates/login.html
Labels: :arrow_up: enhancement

#173 [feat] Boogle Logo/Font 변경
  src/main/resources/static/images/logo.png
  src/main/resources/templates/book/books.html
  src/main/resources/templates/bookreport/book-reports.html
Labels: :arrow_up: enhancement

#174 [feat] 메일링 서비스 중지
  src/main/java/com/kernel360/boogle/global/batch/MailForNewRelease.java
  src/main/java/com/kernel360/boogle/global/config/SpringBatchConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: :arrow_up: enhancement
